name: Deployment Workflow

on:
  workflow_run:
    workflows:
      - Lint, Test & Build
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deployment Step
        run: echo "deploy completed"