name: "updated-files-printer"
on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  printEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get File Data
        id: get-files-data
        shell: bash
        run: |
          echo "${{github.event.head_commit.author.name}}"
          echo "${{github.event.head_commit.id}}"
          echo "${{github.event.head_commit.author.email}}"
