name: "diff-printer"
on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  printEvent:
    runs-on: ubuntu-latest
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "${{github.event.head_commit.author.name}}"
          echo "${{github.event.type}}"
